version: "3.9"

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - '5433:${DB_PORT}'

  app:
    image: grocery-store
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports: 
      - ${PORT}:${PORT}
